library(staphopia)

tag <- get_tag_by_name('mdavid-2016') samples <- get_samples_by_tag(tag$id)

sequence <- paste0('ATGCAATTCAAATTAAAAGAAGAAGAGATTATTAGTTTTTTAGAATTGAAATATCCAG', 'AAAAAGAGTTCGAATATGGTCGTTTGTTAGTTGGACAACATAAACGTGATGATTTAGA', 'TGTTTATTACTTTGGTGATACGTTTTTAATGTGCACGATTATTTCATTCAAGACATTT', 'GAAATTAAAGAAACAGTAGAATTATCATATGATGCTGTTAATCGTATTGTGTTAAAAG', 'ATGGATGGTTATTTAGAAAAATGAGAATAGAAACAATGCAAAAAGTGTTAAAATACGG', 'TACATCTAAATTAATGTTAACTGATTTTCAAAAAGAGAATTATAATAAATATATTCAA', 'GGTCAGAAACAACGCGTGATATTTGAAAATGGCCATTTTGTCTAA')

kmer_hits <- get_kmers_by_sequence(samples$sample_id, sequence)

